export const SOCKET_EVENT = {
  USER_CONNECTED: "USER_CONNECTED",
  USER: {
    SEND_REQUEST_FRIEND: 'SEND_REQUEST_FRIEND',
    UN_FRIEND: 'UN_FRIEND',
    ACCEPT_FRIEND_REQUEST: 'ACCEPT_FRIEND_REQUEST',
    REJECT_FRIEND_REQUEST: 'REJECT_FRIEND_REQUEST',
    CANCEL_FRIEND_REQUEST: 'CANCEL_FRIEND_REQUEST',
    COUNT_FRIEND_REQUEST: 'COUNT_FRIEND_REQUEST',
  },
};